[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/polygon/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/api/alpha/*"
  to = "/.netlify/functions/proxy"
  status = 200
